### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by mohammedouahman** [linkedin-faq/linkedin-quizzes-kodyfire#1]
I tried the same method: 
`**npm install linkedin-quizzes-kodyfire**`
but those resulting kind of vulnerabilities, here is how it looks like:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'boxen@7.0.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'camelcase@7.0.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

up to date, audited 585 packages in 5s

146 packages are looking for funding
  run _npm fund_ for details

23 vulnerabilities (2 low, 6 moderate, 14 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run _npm audit_ for details.

```
I tried both, (npm audit, npm fund) commands, still the same message!
I'm looking forward, guys

Thanks in advance

**Comment by anis-marrouchi** [comment]
Hello @mohammedouahman 
Basically its saying you are required to have node version 14.16 or greater and that your current version is v12.22.9. I recommend you upgrade your node version. According to the node repo, Node v12 did reach end-of-life. 
For you reference checkout the following link [https://github.com/nodejs/Release/#end-of-life-releases](https://github.com/nodejs/Release/#end-of-life-releases)
Let me know if upgrading did solve the issue.

**Comment by mohammedouahman** [comment]
Thank you @anis-marrouchi
I installed the `nodejs  v16.17.0` version, and that's helped to install it, you are a **problem solver**.

**Comment by anis-marrouchi** [comment]
You're welcome @mohammedouahman.
I'm going to close this issue.
